name: Set up Nix
description: Sets up Nix and Nix store caching

runs:
  using: "composite"
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
      with:
        use-flakehub: false
